name: mmCMS Demo API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  laravel-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ./vendor
        key: composer-vendor-${{ hashFiles('**/composer.lock') }}

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run linting
      run: composer run-script check-style

    - name: Run static analysis
      run: composer run-script stan
